openapi: 3.0.3

info:
  title: WASAPhoto API Specification
  description: |-
      This OpenAPI document describes a set of interfaces to allow a WASAPhoto user 
      to interact with the WASAPhoto backend, WASAPhoto is a new social network that
      allows you to share your best moments with friends! 
  version: "v0.0.2"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: /^[A-F0-9]{64}$/i

  schemas:
    Photopost:
      title: Photopost
      type: object
      description: |- 
        A post containing a photo to be displayed in various environments,
        both user profiles and the main feed.
      properties:
        id:
          $ref: '#/components/schemas/SHA256hash'
        identifier:
          $ref: '#/components/schemas/UserID'
        photo:
          $ref: '#/components/schemas/Photo'
        description:
          type: string
          description: Description of the photo
          example: This photo is super cool!
        created_at:
          type: string
          format: date-time
          description: Date and time when the photo was posted
          example: 2020-12-31T23:59:59Z

    Username:
      title: Username
      type: object
      description: |- 
        The username of the user, it must begin with an alphabetical character 
        and can be composed of a number of alphanumeric characters and underscores, 
        with a minimum length of 3 and a maximum length of 32.
      properties:
        username:
          type: string
          pattern: ^[a-zA-Z][a-zA-Z0-9_]{2,32}$ # we don't want to accept any whitespace or weird characters.
          example: "Dario_Loi_123"
    SHA256hash:
      title: SHA256hash
      type: object
      description: |- 
        A generic SHA256 hash, used throughout the API to identify users, photos and more.
      properties:
        hash:
          type: string
          description: The token of the user
          pattern: /^[A-F0-9]{64}$/i
          example: 985981bedf5cc6956330a1e4c39526a8839e8a3ec3adf0f2e3eedd59c359a58d
      
    Photo:
      title: Photo
      format: binary  
      type: string
      description: |- 
        A Base64 encoded photo, used both in posts, profile pictures and 
        generally all over the place, this is WASA*Photo* after all.
      pattern: ^[A-Za-z0-9+/=]*$

    UserID:
      title: UserID #this is basically just a `typedef`
      type: object
      description: |- 
        The token that identifies the user, SHA 256. 
      properties:
        token:
          $ref: '#/components/schemas/SHA256hash'

    User:
      title: User
      type: object
      description: |- 
        A user of the WASAPhoto social network, it contains all *public* information of 
        that user necessary for a quick representation, omitting information such as photos
        in order to reduce the size of the structure.
      properties:
        username:
          $ref: '#/components/schemas/Username'
        profile_photo:
          $ref: '#/components/schemas/Photo'
        created_at:
          type: string
          format: date-time
          description: Date and time when the user was created
          example: 2020-12-31T23:59:59Z
        

    UserList:
      title: UserList
      type: object
      description: |- 
        A list of users, used to return the list of followers and following of a user.
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'

    FollowList:
      title: FollowList
      type: object
      description: |- 
        A Userlist bound to a single user, it is used to represent the Followers/Following
        of a user.
      properties:
        owner:
          $ref: '#/components/schemas/User'
          description: The user whose followers/following are being listed
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
            description: The list of users that follow/is followed by the owner of the list

paths:
  /users:
    post:
      operationId: createUser
      tags:
        - "users"
      summary: Create a new user
      description: |-
        Create a new user in the WASAPhoto system
      requestBody:
        description: |-
          The user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '201':
          description: |-
            The user has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserID'
        '400':
          description: |-
            The username is not valid, it must begin with an alphabetical character,
            must only contain alphanumeric characters and underscores and be of a length
            inbetween 3 and 32.
        '409':
          description: |-
            The username is already taken
  
  /users/{user_name}/profile:
    get:
      operationId: getUserProfile
      tags:
        - "users"
      summary: Get a user's profile
      description: |-
        Get a user's profile, including their username and the list of photos they have posted.
      parameters:
        - name: user_name
          in: path
          description: The username of the user whose profile is being requested
          required: true
          schema:
            $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: |-
            The user's profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    $ref: '#/components/schemas/Username'
                  photos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Photopost'
        '404':
          description: |-
            The user does not exist
    patch:
      operationId: setMyUserName
      tags:
        - "users"
        - "login"
      summary: |-
        Changes the username of an existing user.
      description: |-
        Allows an user to update its username after having already obtained an 
        identifier, this prompts an update of the identifier in order to keep the Bearer
        authentication system in a consistent state, since the identifier depends on 
        the user's name.

        Returns the new identifier in the response body so that the user can continue 
        using the application seamlessly.
      parameters:
        - name: user_name
          in: path
          description: The username of the user that is requesting the update.
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: identifier
          in: header
          description: |- 
            The identifier of the user that is requesting the update, used for 
            authentication purposes.
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      security:
        - bearerAuth: []
      requestBody:
        description: |-
          The new username of the user, **must** be different from the previous one.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: |-
            The user's username has been updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserID'
        '400':
          description: |-
            The username is ill-formed, it must begin with an alphabetical character,
            must only contain alphanumeric characters and underscores and be of a length
            inbetween 3 and 32.
        '401':
          description: |-
            The identifier is not valid, it is either ill-formed or does not belong to the
            user that is requesting the update.
        '409':
          description: |-
            The username is already taken/is identical to the previous
        '404':
          description: |-
            The user that is requesting the update does not exist.


  /users/{user_name}/profile/photos:
    post:
      operationId: uploadPhoto
      summary: Post a photo
      tags:
        - "photos"
      description: |-
        Post a photo to the user's profile
      parameters:
        - name: user_name
          in: path
          description: The username of the user whose profile is being requested
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: identifier
          in: header
          description: The user's identifier
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
        
      security:
        - bearerAuth: []
      requestBody:
        description: |-
          The photo to post
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo:
                  $ref: '#/components/schemas/Photo'
                description:
                  type: string
                  description: Description of the photo
                  example: This photo is super cool!
      responses:
        '201':
          description: |-
            The photo has been posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photopost'
        '400':
          description: |-
            The photo is not valid, it must be a valid base64 encoded image.
        '404':
          description: |-
            The user does not exist
        '401':
          description: |-
            The user is not correctly authenticated (the given ID does not match the user's ID)
    get:
      operationId: getUserPhotos
      summary: Get a user's photos
      tags:
        - "photos"
      description: |-
        Get a user's photos, including their description and the date they were posted,
        useful to populate the feed of their profile.
      parameters:
        - name: user_name
          in: path
          description: The username of the user whose photos are being requested
          required: true
          schema:
            $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: |-
            The user's photos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Photopost'
        '404':
          description: |-
            The user does not exist
  
  /users/{user_name}/profile/photos/{photo_id}:
    get:
      operationId: getPhoto
      summary: Get a photo
      description: |-
        Get an individual photo from the user's profile, useful to populate the feed of other 
        users by picking photos recently posted by other users, also useful to manage 
        the comment section and like counter of a photo.
      tags:
        - "photos"
      parameters:
        - name: user_name
          in: path
          description: The user's name
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: photo_id
          in: path
          description: The photo's id
          required: true
          schema:
            $ref: '#/components/schemas/SHA256hash'
      responses:
        '200':
          description: |-
            The photo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photopost'
        '404':
          description: |-
            Either the requested user of photo id does not exist.
    delete:
      operationId: deletePhoto
      summary: Delete a photo
      description: |-
        Lets the user delete a photo from their profile, the user must authenticate in order 
        to go ahead.
      tags:
        - "photos"
      parameters:
        - name: user_name
          in: path
          description: The user's name
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: photo_id
          in: path
          description: The photo's id
          required: true
          schema:
            $ref: '#/components/schemas/SHA256hash'
        - name: identifier
          in: header
          description: The user's identifier
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      security:
        - bearerAuth: []
      responses:
        '204':
          description: |-
            The photo has been deleted
        '404':
          description: |-
            Either the requested user of photo id does not exist.
        '401':
          description: |-
            The user is not correctly authenticated (the given ID does not match the user's ID)

  /users/{user_name}/following:
    get:
      operationId: getFollowing
      summary: Get the list of users a user is following
      description: |-
        Get the list of users a user is following
      parameters:
        - name: user_name
          in: path
          description: The user's name
          required: true
          schema:
            $ref: '#/components/schemas/Username'
      tags:
        - "followers"
      responses:
        '200':
          description: |-
            The list of users the user is following
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowList'
        '404':
          description: |-
            The user does not exist
    put:
      operationId: followUser
      summary: Follow a user
      description: |-
        Follow a user
      tags:
        - "followers"
      parameters:
        - name: user_name
          in: path
          description: The user's name, used to identify this resource.
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: identifier
          in: header
          description: The user's identifier, used for authentication.
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      requestBody:
        description: |-
          The user to follow
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: |-
            The user has been followed
        '400':
          description: |-
            The follow request is ill-formed.
        '404':
          description: |-
            The user does not exist
        '401':
          description: |-
            The user is not correctly authenticated (the given ID does not match the user's ID)
        
    delete:
      operationId: unfollowUser
      summary: Unfollow a user
      description: |-
        Unfollow a user
      tags:
        - "followers"
      parameters:
        - name: user_name
          in: path
          description: The user's name
          required: true
          schema:
            $ref: '#/components/schemas/Username'
        - name: identifier
          in: header
          description: The user's identifier, used for authentication purposes.
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      requestBody:
        description: |-
          The name user to unfollow
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      security:
        - bearerAuth: []
      responses:
        '204':
          description: |-
            The user has been unfollowed.
        '400':
          description: |-
            The unfollow request is ill-formed.
        '404':
          description: |-
            The user identified by this name does not exist.
        '409':
          description: |-
            The user is not being followed by the user specified in the body of the request.
        '403':
          description: |-
            The user is not correctly authenticated (the given ID does not match the user's ID).

  /users/{user_name}/followers:
    get:
      operationId: getFollowers
      summary: Get the list of users following a user
      description: |-
        Get the list of users following a user
      tags:
        - "followers"
      parameters:
        - name: user_name
          in: path
          description: The user's id
          required: true
          schema:
            $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: |-
            The list of users following the user, the user's name is also 
            aggregated in the list for completeness.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowList'
        '404':
          description: |-
            The user does not exist
    delete:
      operationId: removeFollower
      summary: Remove a follower
      description: |-
        Removes a user from the followers list, useful to  
        enforce the privacy of the user's profile without 
        resorting to a hard ban/block.
      tags:
        - "followers"
      parameters:
        - name: identifier
          in: path
          description: The user's id
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      requestBody:
        description: |-
          The user to unfollow
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserID'
      security:
        - bearerAuth: []
      responses:
        '204':
          description: |-
            The user has been unfollowed
        '400':
          description: |-
            The user to unfollow is not valid
        '404':
          description: |-
            The user does not exist
        '409':
          description: |-
            The user is not being followed

  /session:
    put:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserID'
        '400':
          description: |-
            Login request is ill-formed.